# Generated by Django 2.0.2 on 2018-04-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='previous_message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_message', to='storage.Message'),
        ),
    ]
