# Generated by Django 2.0.2 on 2018-04-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_message_previous_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='sent_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
