# Generated by Django 2.0.1 on 2018-01-27 01:33

from django.conf import settings
from django.db import migrations, models
import my_messages.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=models.SET(my_messages.models.sentient_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
