# Generated by Django 2.0.2 on 2018-03-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0003_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='permissions',
            field=models.CharField(choices=[('4', 'owner'), ('3', 'master'), ('2', 'member'), ('1', 'guest')], default='2', max_length=1),
        ),
    ]
