# Generated by Django 2.0.2 on 2018-03-21 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_messages', '0004_membership_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='permissions',
            field=models.CharField(choices=[('4', 'owner'), ('3', 'master'), ('2', 'member'), ('1', 'guest')], default='2', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('user', 'league')},
        ),
    ]
